## Package configuration
CONFIG = RELEASE

## Default number of threads
NB_THREADS = 2

## List of C++ files that hold your implementation of parallel sort
## Files must have etension .cpp
SORT_CXX_FILES = sort.cpp
## List of C files that hold your implementation of parallel sort
## Files must have etension .c
SORT_CC_FILES =

## Additional compiler flag to pass to C-compiled sources
CFLAGS =
## Additional compiler flags to pass to C++-compiled sources
CXXFLAGS =
## Additional linker flags
CXX_LDFLAGS =

## Number of threads to compile
NB_THREADS = 2

## Task graph description
DRAKE_TASKGRAPH = merge-2.graphml
## Drake target paltform description
DRAKE_PLATFORM = platform-2.dat
## Drake schedule to use
DRAKE_SCHEDULE = ## Let lpt generate a schedule
